devil:                  "The dead grandmother is killing everyone. She is the devil."
the-crucible:           "It's not really about the Salem Witch Trial."
the-others:             "Nicole Kidman is the one who's actually dead. The 'ghosts' are live people in our world."
the-godfather-2:        "Fredo sold Michael out. He broke his heart."
the-crying-game:        "Dil - The beautiful woman is actually a man and it complicates Stephen Rea's character's feelings."
chinatown:              "The girl is Faye Dunaway's sister and daughter. The father, John Huston, was a creep."
the-usual-suspects:     "Verbal is Keyser SÃ¶ze"
the-sixth-sense:        "Bruce Willis is dead the whole time"
unbreakable:            "Samuel L Jackson's charecter is a super villan - whose life mirrors Bruce Willis's. He's very breakable, not unbreakable. He's been orchistrating Bruce Willis's life for years and he derailed the train."
planet-of-the-apes:     "It's our Earth in a dystopic future"
fight-club:             "Tyler Durden is a figment of Ed Norton's imagination"
dallas:                 "The mistress shot J. R."
twin-peaks:             "Laura Palmer's father murdered her. Nadine finally makes silent drape runners."
battlestar-galactica:   "Anders, Tory, Ellen Tigh, Saul Tigh, and Galen Tyrol are the final five cylons."
waiting-for-godot:      "He never shows up."
waiting-for-guffman:    "He never shows up."
the-philadelphia-story: "C. K. Dexter Haven and Tracey get remarried."
the-village:            "It's really the modern day and monsters are the adults. Really - that's it."
the-gods-must-be-crazy: "The gods are crazy"
hamlet:                  "Everyone worth caring about dies."
saw-1:                   "The dead guy on the floor is not dead, and he's Jigsaw."
emily-dickinson:         "You can read most Emily Dickinson poems to the tune of the 'Gilligan's Island' theme."
downton-abbey:           "Lady Edith Dies. Mary and Michael get married. Michael dies an obvious and ham-fisted death at the end of Season 3. It's just a soap opera"